### ISSUE TITLE
Failed test with all latest components at version 2.x

### ISSUE THREAD

**Issue by remicollet** [zendframework/zend-navigation#23] opened 2016-03-12 09:25 UTC
From Fedora CI
https://apps.fedoraproject.org/koschei/package/php-zendframework-zend-navigation

After upgrade of zend-mvc to 2.7.3 and zend-view-2.6.4

    PHPUnit 5.2.10 by Sebastian Bergmann and contributors.
    ...............................................................  63 / 179 ( 35%)
    ............................................................... 126 / 179 ( 70%)
    .................................................PHP Fatal error:  Call to a member function attach() on boolean in /usr/share/php/Zend/View/Helper/Navigation/AbstractHelper.php on line 959

In travis build some component are 3.x (at least zend-stdlib)

**Comment by remicollet** [comment] 2016-03-12 12:08
After some additional test.

This is related to send-event-manager 2.6.3, with 3.0.1 test suite is OK.

**Comment by weierophinney** [comment] 2016-03-17 16:39
I cannot reproduce.

I've created #24 in order to allow testing scenarios like this. With that code in place, I did the following:

```console
$ composer update --prefer-lowest --prefer-stable
$ composer require --dev "zendframework/zend-eventmanager:^2.6.3"
$ ./vendor/bin/phpunit
```

Test run was successful.

The error you're seeing is one I corrected in zendframework/zend-view@341919c (which was part of zendframework/zend-view#52 and released in zend-view 2.6.4) — essentially, prior to that there was no guarantee that the `EventManager` instance composed a `SharedEventManager` instance, and that commit ensured that would always be the case.

Is it possible you're building against an outdated version of zend-view (i.e., prior to 2.6.4)?

**Comment by remicollet** [comment] 2016-03-17 16:44
From a fresh git clone of zend-navigation

```
diff --git a/composer.json b/composer.json
index 76339cc..54ce5e0 100644
--- a/composer.json
+++ b/composer.json
@@ -14,7 +14,7 @@
     },
     "require": {
         "php": "^5.5 || ^7.0",
-        "zendframework/zend-stdlib": "^2.7 || ^3.0"
+        "zendframework/zend-stdlib": "^2.7"
     },
     "require-dev": {
         "zendframework/zend-config": "^2.6",
@@ -24,7 +24,8 @@
         "zendframework/zend-log": "^2.7.1",
         "zendframework/zend-mvc": "^2.7",
         "zendframework/zend-permissions-acl": "^2.6",
-        "zendframework/zend-servicemanager": "^2.7.5 || ^3.0.3",
+        "zendframework/zend-servicemanager": "^2.7.5",
+        "zendframework/zend-eventmanager": "^2.6.3",
         "zendframework/zend-uri": "^2.5",
         "zendframework/zend-view": "^2.6.3",
         "fabpot/php-cs-fixer": "1.7.*",
```

=> phpunit

**Comment by remicollet** [comment] 2016-03-17 16:48
$ grep -E '"(name|version)"' composer.lock            "name": "zendframework/zend-hydrator",

            "version": "1.1.0",
            "name": "zendframework/zend-stdlib",
            "version": "2.7.6",
            "name": "container-interop/container-interop",
            "version": "1.1.0",
            "name": "zendframework/zend-config",
            "version": "2.6.0",
            "name": "zendframework/zend-console",
            "version": "2.6.0",
            "name": "zendframework/zend-diactoros",
            "version": "1.3.4",
            "name": "zendframework/zend-escaper",
            "version": "2.5.1",
            "name": "zendframework/zend-eventmanager",
            "version": "2.6.3",
            "name": "zendframework/zend-filter",
            "version": "2.6.1",
            "name": "zendframework/zend-form",
            "version": "2.7.0",
            "name": "zendframework/zend-http",
            "version": "2.5.4",
            "name": "zendframework/zend-i18n",
            "version": "2.6.0",
            "name": "zendframework/zend-inputfilter",
            "version": "2.6.0",
            "name": "zendframework/zend-loader",
            "version": "2.5.1",
            "name": "zendframework/zend-log",
            "version": "2.7.1",
            "name": "zendframework/zend-mvc",
            "version": "2.7.3",
            "name": "zendframework/zend-permissions-acl",
            "version": "2.6.0",
            "name": "zendframework/zend-psr7bridge",
            "version": "0.2.1",
            "name": "zendframework/zend-servicemanager",
            "version": "2.7.5",
            "name": "zendframework/zend-uri",
            "version": "2.5.2",
            "name": "zendframework/zend-validator",
            "version": "2.6.0",
            "name": "zendframework/zend-view",
            "version": "2.6.4",

**Comment by weierophinney** [comment] 2016-03-17 18:35
> From a fresh git clone of zend-navigation

There's something wrong on your end. Current revision is 57d0bec, and release.2.6.0 is revision 864f044; both versions list constraints on zend-stdlib, and zend-servicemanager that feature the `^2.X || ^3.0` notation. 

BTW, you can use `composer info` to show the installed versions, which is far simpler than using grep. :) Overall, though, those dependencies do not look different than what I had when running `--prefer-lowest --prefer-stable`, which leads me back to my initial comment: you're getting a bad revision for zend-navigation.

**Comment by remicollet** [comment] 2016-03-18 05:19
The diff above is what I change to ensure all versions are "latest" 2.x (not lowest as in your example)

This is also what people get if they requires the full framework (zendframework/zendframework = 2.5), see https://github.com/zendframework/zf2/blob/master/composer.json

Without this change, some versions are 3.x and test suite pass.

**Comment by remicollet** [comment] 2016-03-18 09:49
Digging.

Error is raised in https://github.com/zendframework/zend-view/blob/master/src/Helper/Navigation/AbstractHelper.php#L959

getSharedManager in 2.x may return a boolean false
https://github.com/zendframework/zend-eventmanager/blob/release-2.6/src/EventManager.php#L117

So this should be manage, perhaps like in 
https://github.com/zendframework/zend-view/blob/master/src/HelperPluginManager.php#L378

**Comment by remicollet** [comment] 2016-03-21 07:18
@weierophinney are you able to reproduce with all components at latest 2.x ?

**Comment by weierophinney** [comment] 2016-03-21 16:06
@remicollet I was initially unable to reproduce the issue when doing the following:

- Modified zend-stdlib to only `^2.7`
- Modified zend-servicemanager to only `^2.7.5`

However, when running `composer info`, it indicated that zend-eventmanager v3 was installed, and not v2. So I executed `composer require --dev "zendframework/zend-eventmanager:^2.6.2"`. Once I did that, I saw the issue occur. I'll start investigating shortly to see if I can isolate the problem.

We cannot and will not update the `getSharedManager()` method to return a boolean; it should return null or the shared manager instance only. However, there's clearly cases where we were testing the boolean previously that should be updated (most of these can change to `if (! $events->getSharedManager())`), and I suspect we missed one or two of those.

**Comment by weierophinney** [comment] 2016-03-21 16:25
@remicollet I found the issue: it's a circular dependency problem with the way we're lazy-loading a shared manager between v2 and v3. The issue is within zend-view, so I'll open a PR there and link to this issue from it once I have a solution.

**Comment by weierophinney** [comment] 2016-03-21 18:02
@remicollet I've run the tests using the patch from zendframework/zend-view#55, and that definitely resolves the issue. I'll issue v2.6.5 of zend-view shortly, and then do a patch for zend-navigation upping the minimum version of zend-view to that.

**Comment by weierophinney** [comment] 2016-03-21 18:07
Inadvertently closed via a commit from zend-view; re-opening to do the PR for upping the minimum version in this library.

**Comment by remicollet** [comment] 2016-03-21 18:10
I confirm, issue is fixed. Thanks

(and of course, waiting for the releases ;)

**Comment by weierophinney** [comment] 2016-03-21 18:15
@remicollet I've created #25 now, and once the tests finish, I'll tag v2.6.1 of this repo (zend-view is already tagged at 2.6.5).

I also double-checked locally by running the following:

```console
$ composer update --prefer-lowest --prefer-stable
$ composer require --dev "zendframework/zend-eventmanager:^2.6.3"
$ ./vendor/bin/phpunit
```

All ran fine, so I can definitely confirm the fix. Just want to make sure there are no gotchas before creating the tag.

**Closed** 2016-03-21 18:30 UTC

**Comment by weierophinney** [comment] 2016-03-21 18:32
@remicollet 2.6.1 has now been tagged.

**Comment by remicollet** [comment] 2016-03-22 05:23
FYI, as initial breakage was detected by Fedora CI, here is some news

* zend-navigation is back "green" : https://apps.fedoraproject.org/koschei/package/php-zendframework-zend-navigation
* all the ZF is now "green" : https://apps.fedoraproject.org/koschei/search?q=zendfram

This CI doesn't monitor change in 1 component (what travis do), but change in the dependency tree.

Thanks again.
